// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.7
// source: proto/metrica.proto

package metrica

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 2. Mensaje que el cliente enviará repetidamente en streaming
type LecturaSensor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SensorId      string                 `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	Temperatura   float64                `protobuf:"fixed64,2,opt,name=temperatura,proto3" json:"temperatura,omitempty"` // En grados Celsius
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LecturaSensor) Reset() {
	*x = LecturaSensor{}
	mi := &file_proto_metrica_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LecturaSensor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LecturaSensor) ProtoMessage() {}

func (x *LecturaSensor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrica_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LecturaSensor.ProtoReflect.Descriptor instead.
func (*LecturaSensor) Descriptor() ([]byte, []int) {
	return file_proto_metrica_proto_rawDescGZIP(), []int{0}
}

func (x *LecturaSensor) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *LecturaSensor) GetTemperatura() float64 {
	if x != nil {
		return x.Temperatura
	}
	return 0
}

func (x *LecturaSensor) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// 3. Respuesta final que el servidor calculará y devolverá al cerrar el stream
type ResumenEstadistico struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TotalMuestras       int32                  `protobuf:"varint,1,opt,name=total_muestras,json=totalMuestras,proto3" json:"total_muestras,omitempty"`
	TemperaturaPromedio float64                `protobuf:"fixed64,2,opt,name=temperatura_promedio,json=temperaturaPromedio,proto3" json:"temperatura_promedio,omitempty"`
	TemperaturaMaxima   float64                `protobuf:"fixed64,3,opt,name=temperatura_maxima,json=temperaturaMaxima,proto3" json:"temperatura_maxima,omitempty"`
	TemperaturaMinima   float64                `protobuf:"fixed64,4,opt,name=temperatura_minima,json=temperaturaMinima,proto3" json:"temperatura_minima,omitempty"`
	Mensaje             string                 `protobuf:"bytes,5,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ResumenEstadistico) Reset() {
	*x = ResumenEstadistico{}
	mi := &file_proto_metrica_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumenEstadistico) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumenEstadistico) ProtoMessage() {}

func (x *ResumenEstadistico) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metrica_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumenEstadistico.ProtoReflect.Descriptor instead.
func (*ResumenEstadistico) Descriptor() ([]byte, []int) {
	return file_proto_metrica_proto_rawDescGZIP(), []int{1}
}

func (x *ResumenEstadistico) GetTotalMuestras() int32 {
	if x != nil {
		return x.TotalMuestras
	}
	return 0
}

func (x *ResumenEstadistico) GetTemperaturaPromedio() float64 {
	if x != nil {
		return x.TemperaturaPromedio
	}
	return 0
}

func (x *ResumenEstadistico) GetTemperaturaMaxima() float64 {
	if x != nil {
		return x.TemperaturaMaxima
	}
	return 0
}

func (x *ResumenEstadistico) GetTemperaturaMinima() float64 {
	if x != nil {
		return x.TemperaturaMinima
	}
	return 0
}

func (x *ResumenEstadistico) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

var File_proto_metrica_proto protoreflect.FileDescriptor

const file_proto_metrica_proto_rawDesc = "" +
	"\n" +
	"\x13proto/metrica.proto\x12\ametrica\"l\n" +
	"\rLecturaSensor\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\tR\bsensorId\x12 \n" +
	"\vtemperatura\x18\x02 \x01(\x01R\vtemperatura\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"\xe6\x01\n" +
	"\x12ResumenEstadistico\x12%\n" +
	"\x0etotal_muestras\x18\x01 \x01(\x05R\rtotalMuestras\x121\n" +
	"\x14temperatura_promedio\x18\x02 \x01(\x01R\x13temperaturaPromedio\x12-\n" +
	"\x12temperatura_maxima\x18\x03 \x01(\x01R\x11temperaturaMaxima\x12-\n" +
	"\x12temperatura_minima\x18\x04 \x01(\x01R\x11temperaturaMinima\x12\x18\n" +
	"\amensaje\x18\x05 \x01(\tR\amensaje2_\n" +
	"\x11TelemetriaService\x12J\n" +
	"\x11RegistrarLecturas\x12\x16.metrica.LecturaSensor\x1a\x1b.metrica.ResumenEstadistico(\x01B\x19Z\x17proyecto3/proto/metricab\x06proto3"

var (
	file_proto_metrica_proto_rawDescOnce sync.Once
	file_proto_metrica_proto_rawDescData []byte
)

func file_proto_metrica_proto_rawDescGZIP() []byte {
	file_proto_metrica_proto_rawDescOnce.Do(func() {
		file_proto_metrica_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metrica_proto_rawDesc), len(file_proto_metrica_proto_rawDesc)))
	})
	return file_proto_metrica_proto_rawDescData
}

var file_proto_metrica_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_metrica_proto_goTypes = []any{
	(*LecturaSensor)(nil),      // 0: metrica.LecturaSensor
	(*ResumenEstadistico)(nil), // 1: metrica.ResumenEstadistico
}
var file_proto_metrica_proto_depIdxs = []int32{
	0, // 0: metrica.TelemetriaService.RegistrarLecturas:input_type -> metrica.LecturaSensor
	1, // 1: metrica.TelemetriaService.RegistrarLecturas:output_type -> metrica.ResumenEstadistico
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_metrica_proto_init() }
func file_proto_metrica_proto_init() {
	if File_proto_metrica_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metrica_proto_rawDesc), len(file_proto_metrica_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metrica_proto_goTypes,
		DependencyIndexes: file_proto_metrica_proto_depIdxs,
		MessageInfos:      file_proto_metrica_proto_msgTypes,
	}.Build()
	File_proto_metrica_proto = out.File
	file_proto_metrica_proto_goTypes = nil
	file_proto_metrica_proto_depIdxs = nil
}
