// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.7
// source: proto/metrica.proto

package metrica

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelemetriaService_RegistrarLecturas_FullMethodName = "/metrica.TelemetriaService/RegistrarLecturas"
)

// TelemetriaServiceClient is the client API for TelemetriaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 1. Servicio con Client-Side Streaming
type TelemetriaServiceClient interface {
	// Nota la palabra "stream" en la petición:
	// Múltiples Peticiones (Stream) -> 1 Respuesta final
	RegistrarLecturas(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LecturaSensor, ResumenEstadistico], error)
}

type telemetriaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetriaServiceClient(cc grpc.ClientConnInterface) TelemetriaServiceClient {
	return &telemetriaServiceClient{cc}
}

func (c *telemetriaServiceClient) RegistrarLecturas(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LecturaSensor, ResumenEstadistico], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TelemetriaService_ServiceDesc.Streams[0], TelemetriaService_RegistrarLecturas_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LecturaSensor, ResumenEstadistico]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemetriaService_RegistrarLecturasClient = grpc.ClientStreamingClient[LecturaSensor, ResumenEstadistico]

// TelemetriaServiceServer is the server API for TelemetriaService service.
// All implementations must embed UnimplementedTelemetriaServiceServer
// for forward compatibility.
//
// 1. Servicio con Client-Side Streaming
type TelemetriaServiceServer interface {
	// Nota la palabra "stream" en la petición:
	// Múltiples Peticiones (Stream) -> 1 Respuesta final
	RegistrarLecturas(grpc.ClientStreamingServer[LecturaSensor, ResumenEstadistico]) error
	mustEmbedUnimplementedTelemetriaServiceServer()
}

// UnimplementedTelemetriaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelemetriaServiceServer struct{}

func (UnimplementedTelemetriaServiceServer) RegistrarLecturas(grpc.ClientStreamingServer[LecturaSensor, ResumenEstadistico]) error {
	return status.Error(codes.Unimplemented, "method RegistrarLecturas not implemented")
}
func (UnimplementedTelemetriaServiceServer) mustEmbedUnimplementedTelemetriaServiceServer() {}
func (UnimplementedTelemetriaServiceServer) testEmbeddedByValue()                           {}

// UnsafeTelemetriaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetriaServiceServer will
// result in compilation errors.
type UnsafeTelemetriaServiceServer interface {
	mustEmbedUnimplementedTelemetriaServiceServer()
}

func RegisterTelemetriaServiceServer(s grpc.ServiceRegistrar, srv TelemetriaServiceServer) {
	// If the following call panics, it indicates UnimplementedTelemetriaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelemetriaService_ServiceDesc, srv)
}

func _TelemetriaService_RegistrarLecturas_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TelemetriaServiceServer).RegistrarLecturas(&grpc.GenericServerStream[LecturaSensor, ResumenEstadistico]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemetriaService_RegistrarLecturasServer = grpc.ClientStreamingServer[LecturaSensor, ResumenEstadistico]

// TelemetriaService_ServiceDesc is the grpc.ServiceDesc for TelemetriaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetriaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metrica.TelemetriaService",
	HandlerType: (*TelemetriaServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegistrarLecturas",
			Handler:       _TelemetriaService_RegistrarLecturas_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/metrica.proto",
}
